// ============================================
// Student Portal: Exam Fees & Board Registration Dues (Clean White Theme)
// ============================================

'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useStudentAuth } from '@/context/StudentAuthContext';
import {
  CreditCard,
  CheckCircle2,
  Clock,
  ChevronLeft,
} from 'lucide-react';
import { collection, query, where, getDocs } from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import type { ExamRecord } from '@/types/student';

export default function StudentExamFeesPage() {
  const { student } = useStudentAuth();
  const [exams, setExams] = useState<ExamRecord[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!student?.studentId) return;

    async function loadExamFees() {
      try {
        const q = query(
          collection(db, 'examDetails'),
          where('studentId', '==', student!.studentId)
        );
        const snap = await getDocs(q);
        const list = snap.docs.map((d) => ({ id: d.id, ...d.data() })) as ExamRecord[];
        setExams(list.filter((e) => e.examFee && e.examFee > 0));
      } catch (err) {
        console.error('Error fetching exam fees:', err);
      } finally {
        setLoading(false);
      }
    }

    loadExamFees();
  }, [student?.studentId]);

  return (
    <div className="space-y-4 animate-fade-in max-w-3xl mx-auto">
      {/* Top Bar */}
      <div className="flex items-center gap-3">
        <Link
          href="/student/exams"
          className="w-10 h-10 rounded-xl bg-white border border-slate-200 flex items-center justify-center text-slate-700 active:scale-95 shadow-sm hover:bg-slate-50"
        >
          <ChevronLeft className="w-5 h-5" />
        </Link>
        <div>
          <h2 className="font-bold text-xl sm:text-2xl text-slate-900">
            Board Exam Fees
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Trinity College London & international candidate registration dues
          </p>
        </div>
      </div>

      {/* List */}
      <div className="space-y-3">
        {exams.length === 0 ? (
          <div className="p-8 text-center bg-white rounded-2xl border border-slate-200 shadow-sm space-y-2">
            <CreditCard className="w-10 h-10 text-slate-300 mx-auto" />
            <h4 className="font-bold text-base text-slate-900">
              No Pending Exam Fees
            </h4>
            <p className="text-xs text-slate-500 max-w-xs mx-auto">
              Any official candidate assessment fee for your upcoming grade examination will be listed here once generated by the office.
            </p>
          </div>
        ) : (
          exams.map((exam) => (
            <div
              key={exam.id}
              className="p-5 sm:p-6 rounded-2xl bg-white border border-slate-200 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-3"
            >
              <div className="space-y-1">
                <span className="text-[11px] font-bold uppercase px-2.5 py-0.5 rounded-md bg-blue-50 text-[#2874f0] border border-blue-100">
                  {exam.board || 'Trinity College London'}
                </span>
                <h3 className="font-bold text-base text-slate-900 mt-1.5">
                  {exam.examName} ({exam.grade})
                </h3>
                <p className="text-xs text-slate-500 font-medium">
                  Candidate: {student?.name} • Session: {exam.session || '2026 Assessment'}
                </p>
              </div>

              <div className="text-left sm:text-right">
                <div className="text-xl font-bold text-slate-900">
                  ₹{exam.examFee?.toLocaleString()}
                </div>
                <div className="mt-1">
                  {exam.feeStatus === 'paid' ? (
                    <span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      <span>PAID</span>
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-xs font-bold text-[#fb641b] bg-orange-50 border border-orange-200 px-2.5 py-0.5 rounded-full">
                      <Clock className="w-3.5 h-3.5" />
                      <span>PENDING DUE</span>
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
